services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/hdd:/media:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
